name: Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 'Test Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: 'Setup JDK'
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests
